#!/usr/bin/env bash
# Fetch Watchify secrets from HashiCorp Vault and write .env.runtime for docker compose.
#
# Usage:
#   export VAULT_ADDR=https://vault.example.com:8200
#   export VAULT_TOKEN=s.xxxx
#   bash deploy/vault/load-secrets.sh
#   docker compose -f docker-compose.prod.yml --env-file .env.runtime up -d

set -euo pipefail

VAULT_PATH="${VAULT_PATH:-secret/watchify/prod}"
OUTPUT_FILE="${OUTPUT_FILE:-.env.runtime}"

login_vault() {
  if [[ -n "${VAULT_TOKEN:-}" ]]; then
    export VAULT_TOKEN
    return
  fi
  if [[ -n "${VAULT_ROLE_ID:-}" && -n "${VAULT_SECRET_ID:-}" ]]; then
    VAULT_TOKEN=$(vault write -field=token auth/approle/login \
      role_id="$VAULT_ROLE_ID" \
      secret_id="$VAULT_SECRET_ID")
    export VAULT_TOKEN
    return
  fi
  echo "Set VAULT_TOKEN or VAULT_ROLE_ID + VAULT_SECRET_ID"
  exit 1
}

if ! command -v vault >/dev/null 2>&1; then
  echo "Install Vault CLI: https://developer.hashicorp.com/vault/install"
  exit 1
fi

if [[ -z "${VAULT_ADDR:-}" ]]; then
  echo "Set VAULT_ADDR"
  exit 1
fi

login_vault

vault kv get -format=json "$VAULT_PATH" | python3 -c "
import json, os, sys

out_path = sys.argv[1]
data = json.load(sys.stdin)['data']['data']

mapping = {
    'jwt_secret': 'JWT_SECRET',
    'user_mongo_uri': 'USER_MONGO_URI',
    'upload_mongo_uri': 'UPLOAD_MONGO_URI',
    'watch_mongo_uri': 'WATCH_MONGO_URI',
    'aws_access_key_id': 'AWS_ACCESS_KEY_ID',
    'aws_secret_access_key': 'AWS_SECRET_ACCESS_KEY',
}

lines = ['# Generated by deploy/vault/load-secrets.sh — do not commit']
for vault_key, env_key in mapping.items():
    val = data.get(vault_key, '')
    if val:
        lines.append(f'{env_key}={val}')
lines.extend(['JWT_EXPIRES_IN=7d', 'FRONTEND_PORT=80', 'UPLOAD_PORT=3002'])

with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
os.chmod(out_path, 0o600)
print(f'Wrote {out_path}')
" "$OUTPUT_FILE"

echo "Start: docker compose -f docker-compose.prod.yml --env-file ${OUTPUT_FILE} up -d --build"
